area_info = {'jiangbei': '江北', 'yubei': '渝北', 'nanan': '南岸', 'banan': '巴南', 'shapingba': '沙坪坝',
 'jiulongpo': '九龙坡', 'yuzhong': '渝中', 'dadukou': '大渡口', 'jiangjing': '江津', 'beibei': '北碚',
 'kaizhouqu': '开州区', 'wushanxian1': '巫山县', 'wuxixian': '巫溪县', 'xiushantujiazumiaozuzizhixian': '秀山土家族苗族自治县',
 'youyangtujiazumiaozuzizhixian': '酉阳土家族苗族自治县', 'rongchangqu': '荣昌区',
 'pengshuimiaozutujiazuzizhixian': '彭水苗族土家族自治县', 'zhongxian': '忠县', 'fengjiexian': '奉节县',
 'dianjiangxian': '垫江县', 'chengkouxian': '城口县', 'tongliang': '铜梁', 'bishan': '璧山', 'hechuang': '合川',
 'changshou1': '长寿', 'wanzhou': '万州', 'fuling': '涪陵', 'beibinlu': '北滨路', 'dashiba': '大石坝', 'dazhulin': '大竹林',
 'guanyinqiao': '观音桥', 'haierlu': '海尔路', 'hongensi': '鸿恩寺', 'huahuiyuan': '花卉园', 'huangnibang': '黄泥磅',
 'jiangbeizui': '江北嘴', 'jiazhou': '嘉州', 'longtousi': '龙头寺', 'longxing': '龙兴', 'nanqiaosi': '南桥寺',
 'ranjiaba': '冉家坝', 'shimahe': '石马河', 'shizishan': '石子山', 'songshuqiao': '松树桥', 'wulidian1': '五里店',
 'yuzui': '鱼嘴', 'beihuan': '北环', 'caifuzhongxin1': '财富中心', 'cuiyun': '翠云', 'huayuanxincun': '花园新村',
 'huixing': '回兴', 'konggangxincheng': '空港新城', 'lianglu': '两路', 'lijia': '礼嘉', 'longxi': '龙溪',
 'qibozhongxin': '汽博中心', 'renhe': '人和', 'shuangbei': '双碑', 'xinpaifang': '新牌坊', 'yuanboyuan': '园博园',
 'yuanyang': '鸳鸯', 'yuelai': '悦来', 'zhaomushan': '照母山', 'zhongyanggongyuan': '中央公园', 'bagongli': '八公里',
 'chayuanxinqu': '茶园新区', 'danlonglu': '丹龙路', 'danzishi': '弹子石', 'liugongli': '六公里', 'nanbinlu': '南滨路',
 'nanping': '南坪', 'nanshan3': '南山', 'qigongli': '七公里', 'rongqiaobandao': '融侨半岛', 'sigongli': '四公里',
 'jieshi': '界石', 'lijiatuo1': '李家沱', 'longzhouwan': '龙洲湾', 'nanquan': '南泉', 'ronghuibandao': '融汇半岛',
 'yudong2': '鱼洞', 'bishan1': '璧山', 'chenjiaqiao': '陈家桥', 'ciqikou': '磁器口', 'daping': '大坪',
 'daxuecheng2': '大学城', 'fengtianlu': '凤天路', 'gongrencun': '工人村', 'hualongqiao': '化龙桥', 'laodonglu': '劳动路',
 'lieshimu': '烈士墓', 'lishuwan': '梨树湾', 'sanxiaguangchang': '三峡广场', 'shabinlu': '沙滨路', 'shazhengjie': '沙正街',
 'shiqiaopu': '石桥铺', 'tianxingqiao': '天星桥', 'xiaolongkan': '小龙坎', 'xiyong': '西永', 'yanggongqiao': '杨公桥',
 'yubeilu': '渝碚路', 'zhanxilu': '站西路', 'baguocheng': '巴国城', 'baishiyi': '白市驿', 'binjiangxincheng2': '滨江新城',
 'caiyunhu': '彩云湖', 'chenjiaping': '陈家坪', 'dongbuxincheng': '东部新城', 'dongwuyuan1': '动物园', 'erlang': '二郎',
 'funiuxi': '伏牛溪', 'huangjueping': '黄桷坪', 'huayan': '华岩', 'jiangjinjiaoxian': '江津郊县', 'maoxiangou': '毛线沟',
 'mawangxiang': '马王乡', 'panlong1': '蟠龙', 'shipingqiao': '石坪桥', 'shuangshan': '双山', 'tiaodeng': '跳蹬',
 'xiejiawan': '谢家湾', 'xipeng': '西彭', 'yangjiaping': '杨家坪', 'yuanjiagang': '袁家岗', 'chaotianmen': '朝天门',
 'jiefangbei1': '解放碑', 'lianglukou': '两路口', 'shangqingsi': '上清寺', 'buxingjie': '步行街',
 'dadukouqufu': '大渡口区府', 'jianshecun': '建设村', 'jiugongmiao': '九宫庙', 'binjiangzhonglu': '滨江中路',
 'deganpianqu': '德感片区', 'dongmen1': '东门', 'langshanpianqu': '琅山片区', 'laochengqu': '老城区',
 'xiangruipianqu': '祥瑞片区', 'xiduan': '西段', 'beibeilaochengqu': '北碚老城区', 'caijia': '蔡家',
 'chaoyangqu4': '朝阳区', 'chengbeixinqu': '城北新区', 'chengnanxinqu': '城南新区', 'xiema': '歇马',
 'kaizhouqu1': '开州区', 'wanzhouqu': '万州区', 'yunyang1': '云阳', 'wushanxian3': '巫山县', 'xiushan': '秀山',
 'qianjiang1': '黔江', 'dazu1': '大足', 'rongchang': '荣昌', 'pengshui': '彭水', 'shizhu1': '石柱',
 'wulongxian1': '武隆县', 'liangping1': '梁平', 'zhongxian1': '忠县', 'fengjie': '奉节', 'dianjiangxian1': '垫江县',
 'tongliang 1': '铜梁', 'hechuan': '合川', 'changshou': '长寿', 'fuling1': '涪陵'}

county = ['jiangbei', 'yubei', 'nanan', 'banan', 'shapingba', 'jiulongpo', 'yuzhong', 'dadukou', 'jiangjing', 'beibei', 'kaizhouqu', 'wushanxian1', 'wuxixian', 'xiushantujiazumiaozuzizhixian', 'youyangtujiazumiaozuzizhixian', 'rongchangqu', 'pengshuimiaozutujiazuzizhixian', 'zhongxian', 'fengjiexian', 'dianjiangxian', 'chengkouxian', 'tongliang', 'bishan', 'hechuang', 'changshou1', 'wanzhou', 'fuling']

district = {
    'jiangbei':['beibinlu', 'dashiba', 'dazhulin', 'guanyinqiao', 'haierlu', 'hongensi', 'huahuiyuan', 'huangnibang', 'jiangbeizui', 'jiazhou', 'longtousi', 'longxing', 'nanqiaosi', 'ranjiaba', 'shimahe', 'shizishan', 'songshuqiao', 'wulidian1', 'yuzui'],
    'yubei':['beihuan', 'caifuzhongxin1', 'cuiyun', 'huayuanxincun', 'huixing', 'konggangxincheng', 'lianglu', 'lijia', 'longxi', 'qibozhongxin', 'renhe', 'shuangbei', 'xinpaifang', 'yuanboyuan', 'yuanyang', 'yuelai', 'zhaomushan', 'zhongyanggongyuan'],
    'nanan':['bagongli', 'chayuanxinqu', 'danlonglu', 'danzishi', 'liugongli', 'nanbinlu', 'nanping', 'nanshan3', 'qigongli', 'rongqiaobandao', 'sigongli'],
    'banan':['jieshi', 'lijiatuo1', 'longzhouwan', 'nanquan', 'ronghuibandao', 'yudong2'],
    'shapingba':['chenjiaqiao', 'ciqikou', 'daping', 'daxuecheng2', 'fengtianlu', 'gongrencun', 'hualongqiao', 'laodonglu', 'lieshimu', 'lishuwan', 'sanxiaguangchang', 'shabinlu', 'shazhengjie', 'shiqiaopu', 'tianxingqiao', 'xiaolongkan', 'xiyong', 'yanggongqiao', 'yubeilu', 'zhanxilu'],
    'jiulongpo':['baguocheng', 'baishiyi', 'binjiangxincheng2', 'caiyunhu', 'chenjiaping', 'dongbuxincheng', 'dongwuyuan1', 'erlang', 'funiuxi', 'huangjueping', 'huayan', 'jiangjinjiaoxian', 'maoxiangou', 'mawangxiang', 'panlong1', 'shipingqiao', 'shuangshan', 'tiaodeng', 'xiejiawan', 'xipeng', 'yangjiaping', 'yuanjiagang'],
    'yuzhong':['chaotianmen', 'jiefangbei1', 'lianglukou', 'shangqingsi'],
    'dadukou':['buxingjie', 'dadukouqufu', 'jianshecun', 'jiugongmiao'],
    'jiangjing':['binjiangzhonglu', 'deganpianqu', 'dongmen1', 'langshanpianqu', 'laochengqu', 'xiangruipianqu', 'xiduan'],
    'beibei':['beibeilaochengqu', 'caijia', 'chaoyangqu4', 'chengbeixinqu', 'chengnanxinqu', 'xiema'],
    'kaizhouqu':['kaizhouqu1'],
    'wushanxian1':['wushanxian3'],
    'wuxixian':['yunyang1'],
    'xiushantujiazumiaozuzizhixian':['xiushan'],
    'youyangtujiazumiaozuzizhixian':['qianjiang1'],
    'rongchangqu':['dazu1', 'rongchang'],
    'pengshuimiaozutujiazuzizhixian':['pengshui', 'shizhu1', 'wulongxian1'],
    'zhongxian':['liangping1', 'zhongxian1'],
    'fengjiexian':['fengjie'],
    'dianjiangxian':['dianjiangxian1'],
    'chengkouxian':[],
    'tongliang':['tongliang 1'],
    'bishan':['bishan1'],
    'hechuang':['hechuan'],
    'changshou1':['changshou'],
    'wanzhou':['wanzhouqu'],
    'fuling':['fuling1']
}
